#!/bin/bash
# parse schedule as json
JSON="$(curl -s https://ion.tjhsst.edu/api/schedule?format=json)"
# regex json into class blocks
PARSE="$(echo $JSON | grep -Po  '{\"order\":[^,]*,\"name\":[^,]*,\"start\":[^,]*,\"end\":[^}]*}')"
# split class blocks into array elements
readarray -t ARRAY <<<"$PARSE"
# loop and print
for i in "${ARRAY[@]}"
do
	# pull out name - replace <br> with space
	NAME="$(echo $i | grep -Po '(?<=\"name\":\")[^\"]*' | sed 's/<br>/ /g')"
	#now pull times
	START="$(echo $i | grep -Po '(?<=\"start\":\")[^\"]*' | sed 's/<br>/ /g')"
	END="$(echo $i | grep -Po '(?<=\"end\":\")[^\"]*' | sed 's/<br>/ /g')"
	TEXT="$NAME: \t\t\t$START - $END"
	echo -e "$TEXT"
done
